//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("Script Install Tools")]
[assembly: AssemblyCompany("github.com-trondr")]
[assembly: AssemblyProduct("Script.Install.Tools.Library")]
[assembly: AssemblyCopyright("Copyright © github.com.trondr 2016")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.16091.3.1b7f0ee")]
[assembly: AssemblyVersion("1.0.16091.3")]
[assembly: AssemblyFileVersion("1.0.16091.3")]


